"""
Spec orchestrator - coordinates the iterative spec generation pipeline.
"""

import os
import sys
import json
import time

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from pipeline.frontend.spec.llm_client import call_llm_spec
from state_machine.builder import generate_base_machine, build_state_config, add_transitions, add_transitions_to_branch, normalize_machine, add_workflows_to_machine
from state_machine.post_processing import remove_toplevel_duplicates, complete_missing_branches, clean_unreachable_states, validate_no_critical_patterns, create_missing_target_states
from diagrams.plantuml import generate_plantuml_statechart, generate_plantuml_sequence
from diagrams.markdown import generate_spec_markdown


def run_analysis(
    context_file: str, 
    output_file: str, 
    time_budget: int, 
    analyst_suggestions: dict = None, 
    existing_machine_file: str = None,
    critic_feedback: dict = None
) -> dict:
    """Run the functional analysis and generate spec.md.
    
    ITERATIVE APPROACH:
    1. Load existing machine (if exists)
    2. Pass it to the LLM with suggestions and critic feedback
    3. The LLM modifies the machine instead of regenerating it
    """
    
    start_time = time.time()
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Read context
    with open(context_file, "r", encoding="utf-8") as f:
        context_text = f.read()
    
    # Load existing machine (if any)
    existing_machine = None
    if existing_machine_file and os.path.exists(existing_machine_file):
        with open(existing_machine_file, "r", encoding="utf-8") as f:
            existing_machine = json.load(f)
        print(f"  📦 Existing machine loaded: {len(existing_machine.get('states', {}))} states")
    
    print(f"Context loaded: {len(context_text)} characters")
    if analyst_suggestions:
        print(f"  📋 Analyst suggestions: {len(analyst_suggestions.get('states', []))} states, {len(analyst_suggestions.get('transitions', []))} transitions")
    if critic_feedback:
        critical = critic_feedback.get("summary", {}).get("critical_issues", [])
        print(f"  🚨 Critic feedback: {len(critical)} critical issues")
    print("  🚀 Generating with LLM...")
    
    # Call LLM (iterative approach)
    try:
        llm_data = call_llm_spec(
            context_text, 
            analyst_suggestions=analyst_suggestions,
            existing_machine=existing_machine,
            critic_feedback=critic_feedback
        )
        print(f"  ✅ LLM: {len(llm_data.get('states', []))} states, {len(llm_data.get('transitions', []))} transitions")
    except Exception as e:
        print(f"❌ ERROR: LLM failed: {e}")
        print("   The system cannot work without an LLM.")
        sys.exit(1)
    
    # Determine if we should use parallel states architecture
    # Use parallel if: analyst suggested workflows OR existing machine is parallel
    has_workflows = analyst_suggestions and len(analyst_suggestions.get("workflows", [])) > 0
    is_existing_parallel = existing_machine and existing_machine.get("type") == "parallel"
    use_parallel = has_workflows or is_existing_parallel
    
    # Build machine using modular builder
    machine = None
    
    if existing_machine:
        # Start from existing machine
        machine = existing_machine.copy()
        machine["states"] = dict(existing_machine.get("states", {}))
        
        # Add new states from LLM suggestions
        for state in llm_data.get("states", []):
            state_name = state["name"]
            
            # Ignore dot-notation clones generated by LLM (e.g. success.dashboard)
            if "." in state_name:
                continue
                
            if state_name not in machine["states"]:
                machine["states"][state_name] = build_state_config(state)
            else:
                # Update existing state
                existing_entry = machine["states"][state_name].get("entry", [])
                new_entry = state.get("entry_actions", [])
                machine["states"][state_name]["entry"] = list(set(existing_entry + new_entry))
                
                existing_exit = machine["states"][state_name].get("exit", [])
                new_exit = state.get("exit_actions", [])
                machine["states"][state_name]["exit"] = list(set(existing_exit + new_exit))
                
                # Preserve or add hierarchical sub-states
                sub_states = state.get("sub_states", [])
                if sub_states:
                    new_config = build_state_config(state)
                    machine["states"][state_name]["initial"] = new_config["initial"]
                    existing_subs = machine["states"][state_name].get("states", {})
                    existing_subs.update(new_config.get("states", {}))
                    machine["states"][state_name]["states"] = existing_subs
        
        # Add transitions
        add_transitions(machine, llm_data.get("transitions", []))
    else:
        # Generate from scratch with parallel architecture if workflows exist
        machine = generate_base_machine(use_parallel=use_parallel)
        
        if use_parallel:
            # In parallel mode, states go into navigation branch
            nav_branch = machine["states"]["navigation"]
            for state in llm_data.get("states", []):
                state_name = state["name"]
                nav_branch["states"][state_name] = build_state_config(state)
            
            # Add transitions to navigation branch
            add_transitions_to_branch(machine, llm_data.get("transitions", []))
            
            # Add workflows to active_workflows branch
            if has_workflows:
                workflows = analyst_suggestions.get("workflows", [])
                add_workflows_to_machine(machine, workflows)
                print(f"  🔄 Added {len(workflows)} workflows to active_workflows branch")
        else:
            # Legacy flat mode
            for state in llm_data.get("states", []):
                state_name = state["name"]
                machine["states"][state_name] = build_state_config(state)
            
            # Add transitions
            add_transitions(machine, llm_data.get("transitions", []))
    
    # Normalize machine
    machine = normalize_machine(machine)
    
    # Post-processing: remove top-level duplicate states (before BFS cleanup)
    machine = remove_toplevel_duplicates(machine)
    
    # Post-processing: complete missing transition branches
    machine = complete_missing_branches(machine)
    
    # Post-processing: create missing target states to prevent black holes
    machine = create_missing_target_states(machine)
    
    # Post-processing: remove unreachable states and XState keywords
    machine = clean_unreachable_states(machine)
    
    # Post-processing: validate against critical rules 15, 16, 17
    violations = validate_no_critical_patterns(machine)
    if violations:
        print(f"\n  ⚠️  CRITICAL RULE VIOLATIONS DETECTED ({len(violations)}):")
        for v in violations:
            print(f"    ❌ {v}")
        print(f"\n  💡 These violations will be reported to the critic for the next iteration.")
        print(f"     The LLM should fix them when it sees the critic feedback.\n")
    else:
        print(f"  ✅ No critical rule violations (rules 15, 16, 17 passed)")
    
    print(f"Generated state machine: {len(machine['states'])} states")
    
    # Generate diagrams using modular components
    statechart = generate_plantuml_statechart(machine)
    flows = llm_data.get("flows", [])
    sequence = generate_plantuml_sequence(flows)
    
    # Generate markdown spec using modular component
    spec_content = generate_spec_markdown(
        machine=machine,
        llm_data=llm_data,
        statechart=statechart,
        sequence=sequence,
        violations=violations,
    )
    
    # Write spec
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(spec_content)
    
    # Write XState
    xstate_file = output_file.replace(".md", "_machine.json")
    with open(xstate_file, "w", encoding="utf-8") as f:
        json.dump(machine, f, indent=2)
    
    elapsed = time.time() - start_time
    
    metrics = {
        "states_count": len(machine["states"]),
        "transitions_count": sum(len(s.get("on", {})) for s in machine["states"].values()),
        "edge_cases_count": len(llm_data.get("edge_cases", [])),
        "error_types_count": len(llm_data.get("error_handling", [])) or 1,
        "elapsed_seconds": elapsed,
        "spec_file": output_file,
        "machine_file": xstate_file,
    }
    
    return metrics