"""
Rules for automatic functional analysis.

Contains ONLY structural rules (WHAT must exist), no hardcoded content.
All names, descriptions, behaviors are generated by the LLM.

The rules say: "there must be an authentication flow"
The LLM decides: "login_form → login_pending → login_success"
"""

from typing import Dict, List, Set


# ---------------------------------------------------------------------------
# Structural Rules (WHAT must exist, not WHAT it's called)
# ---------------------------------------------------------------------------

RULES: Dict[str, dict] = {
    "authentication": {
        "description": "Every app with users must have an authentication flow",
        "must_have_states": [
            "a_state_for_credential_input",
            "a_state_for_waiting_for_response",
            "a_state_for_success",
            "a_state_for_failure",
        ],
        "must_have_transitions": [
            {"from": "input_state", "to": "waiting_state", "event": "SUBMIT_CREDENTIALS"},
            {"from": "waiting_state", "to": "success_state", "event": "AUTH_SUCCESS"},
            {"from": "waiting_state", "to": "failure_state", "event": "AUTH_FAILED"},
        ],
        "edge_cases_to_check": [
            "forgotten_password_must_have_recovery_flow",
            "account_locked_after_too_many_attempts",
            "expired_session_must_allow_relogin",
            "login_from_multiple_devices_simultaneously",
        ],
        "questions_to_ask": [
            "After how many failed attempts is the account locked?",
            "How long does the session token last?",
            "Can the user be logged in on multiple devices?",
        ],
    },
    
    "form_handling": {
        "description": "Every form must handle input, validation, submit, success, error",
        "must_have_states": [
            "a_state_for_form_editing",
            "a_state_for_validation",
            "a_state_for_submit_waiting",
            "a_state_for_success",
            "a_state_for_error",
        ],
        "must_have_transitions": [
            {"from": "edit_state", "to": "validation_state", "event": "VALIDATE"},
            {"from": "validation_state", "to": "submit_state", "event": "SUBMIT"},
            {"from": "submit_state", "to": "success_state", "event": "SUBMIT_SUCCESS"},
            {"from": "submit_state", "to": "error_state", "event": "SUBMIT_ERROR"},
            {"from": "any_intermediate_state", "to": "initial_state", "event": "CANCEL"},
        ],
        "edge_cases_to_check": [
            "double_click_on_submit_button",
            "inline_vs_on_submit_validation",
            "browser_close_during_submit",
            "data_loss_due_to_connection_loss",
            "missing_required_fields",
        ],
        "questions_to_ask": [
            "Is validation inline (on blur) or only on submit?",
            "What happens if the user closes the browser during submit?",
            "Can the form be saved as a draft?",
        ],
    },
    
    "error_handling": {
        "description": "Every async operation must handle errors, timeouts, cancellation",
        "must_have_states": [
            "a_state_for_generic_error",
            "a_state_for_timeout",
            "a_state_for_cancellation",
        ],
        "must_have_transitions": [
            {"from": "any_async_state", "to": "error_state", "event": "ERROR"},
            {"from": "any_async_state", "to": "timeout_state", "event": "TIMEOUT"},
            {"from": "any_async_state", "to": "cancelled_state", "event": "CANCEL"},
            {"from": "error_state", "to": "retry_state", "event": "RETRY"},
        ],
        "edge_cases_to_check": [
            "network_error_during_critical_operation",
            "server_timeout",
            "rate_limit_reached",
            "server_500_error",
            "corrupted_or_malformed_data",
        ],
        "questions_to_ask": [
            "Can the user retry after an error? How many times?",
            "What happens if the error is irreversible?",
            "How do you communicate the error to the user (toast, modal, page)?",
        ],
    },
    
    "navigation": {
        "description": "Every app must handle navigation between screens, back, deep links",
        "must_have_states": [
            "a_main_home_state",
            "a_detail_state",
            "a_loading_state",
        ],
        "must_have_transitions": [
            {"from": "home_state", "to": "detail_state", "event": "NAVIGATE_TO_DETAIL"},
            {"from": "detail_state", "to": "home_state", "event": "GO_BACK"},
            {"from": "home_state", "to": "loading_state", "event": "LOAD_DATA"},
        ],
        "edge_cases_to_check": [
            "back_button_during_loading",
            "deep_link_to_nonexistent_page",
            "rapid_double_navigation",
            "state_loss_on_orientation_change",
        ],
        "questions_to_ask": [
            "What happens if the user presses back during an operation?",
            "How do you handle deep links if the user is not logged in?",
            "Is the screen state preserved when returning?",
        ],
    },
    
    "empty_states": {
        "description": "Every list or search must handle empty states",
        "must_have_states": [
            "a_state_for_empty_results",
            "a_state_for_first_use",
        ],
        "must_have_transitions": [
            {"from": "search_state", "to": "empty_state", "event": "NO_RESULTS"},
            {"from": "empty_state", "to": "alternative_action_state", "event": "TAKE_ACTION"},
        ],
        "edge_cases_to_check": [
            "search_with_no_results",
            "empty_list_on_first_launch",
            "all_data_deleted_at_once",
        ],
        "questions_to_ask": [
            "What does the user see when there are no results?",
            "Do you offer alternative actions when the list is empty?",
            "How do you guide the user on first use?",
        ],
    },
    
    "notifications": {
        "description": "Every app must handle notifications and alerts",
        "must_have_states": [
            "a_state_for_notification_center",
            "a_state_for_notification_detail",
        ],
        "must_have_transitions": [
            {"from": "any_state", "to": "notification_state", "event": "RECEIVE_NOTIFICATION"},
            {"from": "notification_state", "to": "detail_state", "event": "OPEN_NOTIFICATION"},
        ],
        "edge_cases_to_check": [
            "too_many_simultaneous_notifications",
            "notification_for_already_completed_action",
            "notifications_disabled_by_user",
        ],
        "questions_to_ask": [
            "How do you group multiple notifications?",
            "What happens if you tap a notification for an already completed action?",
            "Can the user disable notifications?",
        ],
    },
}


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def get_all_must_have_states() -> Set[str]:
    """Returns all states that MUST exist (descriptive, not specific names)."""
    states = set()
    for rule in RULES.values():
        states.update(rule.get("must_have_states", []))
    return states


def get_all_must_have_transitions() -> List[dict]:
    """Returns all transitions that MUST exist."""
    transitions = []
    for rule in RULES.values():
        transitions.extend(rule.get("must_have_transitions", []))
    return transitions


def get_all_edge_cases_to_check() -> Set[str]:
    """Returns all edge cases that MUST be verified."""
    edge_cases = set()
    for rule in RULES.values():
        edge_cases.update(rule.get("edge_cases_to_check", []))
    return edge_cases


def get_all_questions() -> Set[str]:
    """Returns all questions that MUST be asked."""
    questions = set()
    for rule in RULES.values():
        questions.update(rule.get("questions_to_ask", []))
    return questions


def validate_against_rules(machine: dict) -> dict:
    """
    Validate a state machine against the rules.
    Returns a report of what's missing.
    
    Args:
        machine: XState state machine
        
    Returns:
        Validation report with missing states and transitions
    """
    states = set(machine.get("states", {}).keys())
    transitions = []
    for state_name, state_config in machine.get("states", {}).items():
        for event, target in state_config.get("on", {}).items():
            if isinstance(target, dict):
                target_state = target.get("target", "")
            else:
                target_state = target
            transitions.append((state_name, target_state, event))
    
    missing_states = []
    missing_transitions = []
    
    for rule_name, rule in RULES.items():
        # Check states (descriptive - LLM decides specific names)
        for required_state_desc in rule.get("must_have_states", []):
            # We don't check exact names, but look for states containing keywords
            keywords = required_state_desc.lower().replace("a_state_for_", "").replace("a_", "").replace("_", " ").split()
            found = False
            for state in states:
                state_lower = state.lower()
                if any(kw in state_lower for kw in keywords if len(kw) > 3):
                    found = True
                    break
            if not found:
                missing_states.append(f"[{rule_name}] {required_state_desc}")
        
        # Check transitions
        for required_trans in rule.get("must_have_transitions", []):
            event = required_trans.get("event", "")
            found = any(e == event for _, _, e in transitions)
            if not found:
                missing_transitions.append(f"[{rule_name}] {event}")
    
    return {
        "missing_states": missing_states,
        "missing_transitions": missing_transitions,
        "is_valid": len(missing_states) == 0 and len(missing_transitions) == 0,
    }


# ---------------------------------------------------------------------------
# Main (for testing)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=== Rules ===\n")
    for rule_name, rule in RULES.items():
        print(f"## {rule_name}: {rule['description']}")
        print(f"   Required states: {len(rule['must_have_states'])}")
        print(f"   Required transitions: {len(rule['must_have_transitions'])}")
        print(f"   Edge cases: {len(rule['edge_cases_to_check'])}")
        print()
    
    print(f"Total required states: {len(get_all_must_have_states())}")
    print(f"Total required transitions: {len(get_all_must_have_transitions())}")
    print(f"Total edge cases: {len(get_all_edge_cases_to_check())}")
    print(f"Total questions: {len(get_all_questions())}")